### ISSUE TITLE
I need to contact you for a job

### ISSUE THREAD

**Issue by granados12** [HechengLi/reverse-engineering-notes#1]
Hello bro I see that you work with reverse engineering of cocos2dx, I want to decompile some files of a game also of cocods2dx, and I would like you to collaborate with me, I pay you for the decompilation service
You can contact me through discord YearsGames#3404

**Comment by chrisli-03** [comment]
> granados12

May I ask what game you are working on? And you know Im not an expert, this is just my learning notes right?
