### ISSUE TITLE
Help me :)

### ISSUE THREAD

**Issue by agratushniy** [HechengLi/reverse-engineering-notes#2]
Hello, can you help me with same problem?

**Comment by chrisli-03** [comment]
> Hello, can you help me with same problem?

what problem?

**Comment by agratushniy** [comment]
I have an android application with encrypted lua sources. I need your help in decrypting them. Can you help me?

**Comment by chrisli-03** [comment]
> I have an android application with encrypted lua sources. I need your help in decrypting them. Can you help me?

hm sorry I don't want to involve in any illegal activities
